# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = WSI
TEMPLATE = app

DEFINES += QT_DLL QT_WIDGETS_LIB

INCLUDEPATH += ../../Model/ \
    ../../CreateMassArray/ \
    ../../InfoAboutAccessObjs/ \
    ../../ObjsMap/ \
    ../../../WSI/ \
    ../../View/

SOURCES += \
    main.cpp
